modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="criogeniakorps"
version="1.1"
displayName="Criogenia Korps"
description="Mod Comissionado por Shune! @yxmashu"

[[dependencies.criogeniakorps]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.criogeniakorps]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
